# Generated by Django 5.0.1 on 2024-10-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='email',
            new_name='phone_number',
        ),
    ]
