# Generated by Django 5.0.1 on 2024-01-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_pitch', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about_description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_title', models.CharField(max_length=100)),
                ('benefit_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('benefit_description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=150)),
                ('reminder', models.TextField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('problem_statement', models.TextField(max_length=150)),
                ('solution_statement', models.TextField(max_length=300)),
                ('pitch', models.TextField(max_length=150)),
                ('address', models.TextField()),
                ('location', models.TextField()),
                ('county', models.TextField()),
                ('countryt', models.TextField()),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('featured', models.BooleanField(default=False)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.TextField(blank=True, max_length=150)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=170)),
                ('price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('feaure1', models.CharField(blank=True, max_length=170, null=True)),
                ('feaure2', models.CharField(blank=True, max_length=170, null=True)),
                ('feaure3', models.CharField(blank=True, max_length=170, null=True)),
                ('feaure4', models.CharField(blank=True, max_length=170, null=True)),
                ('feaure5', models.CharField(blank=True, max_length=170, null=True)),
                ('feaure6', models.CharField(blank=True, max_length=170, null=True)),
                ('recommended', models.BooleanField(default=False)),
                ('limited_feature', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('service_title', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_name', models.CharField(max_length=100)),
                ('statistic_icon', models.CharField(max_length=100)),
                ('statistic_number', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=10)),
                ('testimonial_proffession', models.CharField(max_length=100)),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('testimonial_message', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
