# Generated by Django 5.0.1 on 2024-02-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0002_companyinfor_linkedin_alter_calltoaction_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
