# Generated by Django 5.0.1 on 2024-02-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0003_aboutus_youtube_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfor',
            old_name='countryt',
            new_name='country',
        ),
    ]
