# Generated by Django 5.0.1 on 2024-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0004_rename_countryt_companyinfor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
