# Generated by Django 5.0.1 on 2024-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0007_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='twiter',
            new_name='twitter',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
