# Generated by Django 5.0.1 on 2024-03-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0008_rename_twiter_staff_twitter_staff_staff_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='feaure1',
            new_name='feature1',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='feaure2',
            new_name='feature2',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='feaure3',
            new_name='feature3',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='feaure4',
            new_name='feature4',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='feaure5',
            new_name='feature5',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='feaure6',
            new_name='feature6',
        ),
    ]
