# Generated by Django 5.0.1 on 2024-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0010_lead_company_name_lead_country_lead_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compaarison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
