# Generated by Django 5.0.1 on 2024-10-25 15:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0012_whyus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_pitch',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='companyinfor',
            name='pitch',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='termsandcondition',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='first_point_overview',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='overview',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='second_point_overview',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='third_point_overview',
            field=models.TextField(max_length=400),
        ),
    ]
