# Generated by Django 5.0.1 on 2024-10-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_company', '0013_alter_aboutus_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='software_company.lead')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software_company.pricing')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('month', models.DateField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('customer_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software_company.customerplan')),
            ],
        ),
    ]
